<?php
/**
 * Test script that uses lemurdb.php to build a SELECT with AND/OR/LIKE
 * and multiple BETWEEN, then prints SQL, params, and results.
 *
 * PHP 7.x compatible.
 */

require_once __DIR__ . '/lemurdb.php';

// --- Connection config (adjust to your environment) ---
$config = [
    'driver' => 'mysql', // or 'pgsql'
    'host' => '127.0.0.1',
    'port' => 3306,
    'db' => 'moodle_esp',
    'username' => 'manager',
    'password' => 'Manager2026x',
    'charset' => 'utf8mb4',
    'prefix' => 'mdl5g_',
];


$db = Database::getInstance($config);

// Build query with AND / OR / LIKE and multiple BETWEEN
$qb = $db->query('products')
    ->select(['id', 'name', 'price', 'created_at'])
    ->where(['status' => 1])
    ->orWhere(['category' => 'electronics'])
    ->like('name', '%usb%')
    ->between('price', 10.00, 250.00)
    ->between('created_at', '2025-01-01', '2025-12-31')
    ->orderby('created_at DESC')
    ->limit(20);

// Print SQL + params generated by lemurdb
echo "SQL (lemurdb):\n" . $qb->toSql() . "\n\n";
echo "Params (lemurdb):\n";
print_r($qb->getParams());
echo "\n";

// Execute and print results (disabled for construction-only test)
// $rows = $qb->get();
// echo "Results:\n";
// print_r($rows);
